#!/usr/bin/env bash

BASE_DIR=$(dirname "$0")
SRC = $BASE_DIR"vba-blocks.app"
APP = "/Applications/vba-blocks.app"

# Copy vba-blocks.app to Applications
cp $SRC $APP

# Add bin to .profile / .bash_profile
BIN = $APP"/bin"
PATH = "export PATH=\"$PATH:"BIN"\""
PROFILE = "~/.profile"
BASH_PROFILE = "~/.bash_profile"

if [grep -vqs PATH PROFILE] then
  echo PATH >> PROFILE
fi
if [-f BASH_PROFILE] && [grep -vqs PATH BASH_PROFILE] then
  echo PATH >> BASH_PROFILE
fi

# TODO Create symlink to add-ins in helpful place
